name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.2 # This is the action
        with:
          heroku_api_key: cfc0e4db-f441-4c69-af36-f3ec812fe6ac
          heroku_app_name: "doitappuwf" #Must be unique in Heroku
          heroku_email: "db119@students.uwf.edu"
          branch: "master" #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
          dontuseforce: false #OPTIONAL and DEFAULT - false
          usedocker: false #OPTIONAL and DEFAULT - false
          appdir: "server" #OPTIONAL and DEFAULT - "". This is useful if the api you're deploying is in a subfolder
